# For a quick dateStringFrom check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);



###11111

POST http://localhost:8080/owner/add
Content-Type: application/json


{
  "companyName":"тест3",
  "firstName": "test3",
  "lastName": "test3",
  "contacts": {
    "phones": [
      {
        "phone": "55555555532",
        "typeContact": "Work"
      }
    ]
  }
}

###22222

###11111

POST http://localhost:8080/owner/add
Content-Type: application/json


{
  "companyName":"тест3",
  "firstName": "test3",
  "lastName": "test3",
  "contacts": {
    "emails": [
      {
        "email": "55555555532",
        "typeContact": "Work"
      }
    ]
  }
}

###22222

DELETE http://localhost:8080/owner/delete/115

###33333
GET http://localhost:8080/item/getByOwner/115

###44444
POST http://localhost:8080/category/add
Content-Type: application/json

{
  "categoryName": "new category0000"
}

###6666
POST http://localhost:8080/item/add
Content-Type: application/json

{
  "title": "шарика ручкы",
  "count": 1,
  "price": 5,
  "productOwnerId": 115

}

###7777

POST http://localhost:8080/item/update
Content-Type: application/json

{
  "itemId": 90,
  "count": 4000
}

###8888

POST http://localhost:8080/item/withdraw
Content-Type: application/json

{
	"itemList": [
	{
		"itemId": 81,
		"count": 1,
		"productOwnerId": 84
	},
      {
        "itemId": 81,
        "count": 0,
        "productOwnerId": 84
      }
     ]
}

###9999

POST http://localhost:8080/item/totalStatistic
Content-Type: application/json

{
  "period": "CURRENT_DAY",
  "typeOperation": "ADD"
}


###10
GET http://localhost:8080/item/topStatistic
###
