# For a quick dateStringFrom check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/owner/add
Content-Type: application/json

{
  "companyName":"тест",
  "firstName": "ererer",
  "contacts": {
    "phones": [
      {
        "phone": "55555555532",
        "typeId": 20
      },
      {
        "phone": "1234455",
        "typeId": 20
      }

    ]
  }
}

###

DELETE http://localhost:8080/owner/delete/83

###
GET http://localhost:8080/item/getByOwner/83
###

POST http://localhost:8080/category/add
Content-Type: application/json

{
  "categoryName": "new category0000"
}

###
POST http://localhost:8080/item/add
Content-Type: application/json

{
  "title": "newItem",
  "count": 9,
  "price": 400,
  "productOwnerId": 83,
  "dateAdd": "10/08/2019 11:36"
}

###

POST http://localhost:8080/item/update
Content-Type: application/json

{
  "itemId": 38,
  "count": 7,
  "price": 10,
  "productOwnerId": 83
}

###

POST http://localhost:8080/item/totalStatistic
Content-Type: application/json

{
  "period": "CURRENT_DAY",
  "typeOperation": "UPDATE"
}



###

#+ add new product owner
#• remove product owner (only product owners without any item currently
#stored at warehouse could be removed
#• store new item (items could be stored only for already known product
#owners)
#• withdraw item from warehouse (it is common situation with withdrawing
#several different items for one product owner at once)
#• provide list of all items for given product owner

• prove list of active product owners

• provide statistic information about amount and total cost of items stored
and withdrawn for the last day/month

• provide statistic information about active product owners: list of top 5
product owners according to the total cost of items currently stored at warehouse, sorted by total price, starting with the biggest one